import authorimg from "../assets/authurImg.png";
export const blog = [
  {
    id: "1",
    title: "is crypto the future of money svdj ",
    author: "Ugbor Faith lowo",
    category: "savings",
    tags: "Investment",
    date: "10/08/2023",
    time: "8:00 AM",
    authorimg: authorimg,
  },
  {
    id: "2",
    title: "is crypto the future of money hvxcjx ",
    author: "Ugbor Faith lowo",
    category: "savings",
    tags: "Investment",
    date: "10/08/2023",
    time: "8:00 AM",
    authorimg: authorimg,
  },
  {
    id: "3",
    title: "is crypto the future of money bhsvc ",
    author: "Ugbor Faith lowo",
    category: "savings",
    tags: "Investment",
    date: "10/08/2023",
    time: "8:00 AM",
    authorimg: authorimg,
  },
  {
    id: "4",
    title: "is crypto the future of money jhvdf ",
    author: "Ugbor Faith lowo",
    category: "savings",
    tags: "Investment",
    date: "10/08/2023",
    time: "8:00 AM",
    authorimg: authorimg,
  },
  {
    id: "4",
    title: "is crypto the future of money jhvdf ",
    author: "Ugbor Faith lowo",
    category: "savings",
    tags: "Investment",
    date: "10/08/2023",
    time: "8:00 AM",
    authorimg: authorimg,
  },
];
